package com.webpieces.http2parser.api.dto.lib;

public enum Http2MsgType {
	GOAWAY, PING, SETTINGS, WINDOW_UPDATE, DATA, PUSH_PROMISE, PRIORITY, RST_STREAM, UNKNOWN, 
	REQUEST_HEADERS, RESPONSE_HEADERS, TRAILING_HEADERS,
    ;

}
