package org.webpieces.ssl.impl;

public enum ActionEnum {
	BEGIN_HANDSHAKE_START, BEGIN_HANDSHAKE_END, 
	FEED_ENCRYPTED_START, FEED_ENCRYPTED_END, 	
	FEED_PLAIN_START, FEED_PLAIN_END, 
	
	CLOSE_START, CLOSE_END,
	
	NEED_TASK, FAIL,
	WRAP_START, WRAP_END, 
	WRAP2_START, WRAP2_END, 
	UNWRAP_START, UNWRAP_END, 

}
