#!/bin/bash

BRANCH=`git rev-parse --abbrev-ref HEAD`

if [[ $BRANCH != "review_"* ]]; then
   echo "You named your branch wrong for async review.  It will be pushed as $BRANCH still, BUT It must start with review_<YOUR NAME> to start with"
   exit 1
fi

function evil_git_dirty {
  [[ $(git diff --shortstat 2> /dev/null | tail -n1) != "" ]] && echo "*"
}

NUM_FILES="$(evil_git_dirty)"
echo "Num files not committed=$NUM_FILES"
if [[ "$NUM_FILES" == "*" ]]; then
   echo ""
   echo "You have outstanding files that are not committed.  commit first or stash, then you can push"
   echo ""
   git status
   echo "----------------------------------------------------------------------------------------------"
   echo "You have outstanding files that are not committed.  commit first or stash, then you can push"
   echo "----------------------------------------------------------------------------------------------"
   exit 1
fi

#Make sure developer has latest master so he doesn't push to CI without merging first
updateToOriginMaster.sh

if [ $? -eq 0 ]
then
   echo "Successfully merged master"
else
   exit 1
fi

monobuild.sh
if [ $? -eq 0 ]
then
   echo "Successfully merged master"
else
   exit 1
fi


SUBMIT_BRANCH="submit${BRANCH:6}"
ASYNC_REVIEW_BRANCH="asyncreview${BRANCH:6}"

#submit the branch for an async review to be reviewed later...
echo "Pushing the branch for review to origin/$BRANCH"
git push -u origin "$BRANCH:$ASYNC_REVIEW_BRANCH"

if [ $? -eq 0 ]
then
   echo "Successfully pushed $ASYNC_REVIEW_BRANCH"
else
   echo "FAILURE pushing!!! perhaps branch exists already"
   exit 1
fi

#submit the $SUBMIT_BRANCH to CI to build it...
echo "Pushing the branch to be built to remote branch origin/$SUBMIT_BRANCH"
git push -u origin "$BRANCH:$SUBMIT_BRANCH"

if [ $? -eq 0 ]
then
   echo "Successfully pushed $SUBMIT_BRANCH"
else
   echo "FAILURE pushing!!! perhaps branch exists already"
   exit 1
fi

git checkout master

git branch -d "$BRANCH"
