/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package victor;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        int deanVar = 0;
        System.out.println("hi there="+deanVar);

        System.out.println(new App().getGreeting());
        System.out.println(new App().getGreeting());
        System.out.println(new App().getGreeting());
        System.out.println(new App().getGreeting());
        System.out.println(new App().getGreeting());
        System.out.println(new App().getGreeting());

    }
}
